name: flutter_complete_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.9.0
  retrofit_generator: ^10.0.1
  freezed: ^3.2.3
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.2

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
         - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
         - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
         - asset: assets/fonts/inter/Inter_28pt-Regular.ttf


