default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart"
    firebase_app_distribution(
    app: "1:929929450086:android:fbb33458edf154a72393a7",
    firebase_cli_token: "1//03aVqg9RjLh_cCgYIARAAGAMSNgF-L9IrLaYGaWM5T67jjfF1Lk1qMQsFzAbpoLZgLrOW5u-dIioX4na5Im5cF7wOJ4aftUYcCw",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    release_notes: "First FastLane App Distribution",
    testers:"nanabamin33@gmail.com"
  )
   end
end
